### PR TITLE
Added GLFW

### PR DESCRIPTION
**Pull request by vssukharev**

### CODE REVIEW

**Comment by lerno** [comment]
Can you add it to the CI too? Otherwise it will not be packaged.

**Comment by vssukharev** [comment]
I'm sorry, you mean library ZIP archive to assets?

**Comment by lerno** [comment]
Yes, look here: https://github.com/c3lang/vendor/blob/main/.github/workflows/main.yml

You only need to copy paste from one of the others and update the names and paths.

**Comment by vssukharev** [comment]
I've made commit and also slightly changed README (added vulkan as available library too)

**Comment by lerno** [comment]
Wait, I realize this was added as a sub module, can you please add it as a regular directory.

**Comment by vssukharev** [comment]
That's strange as there wasn't .gitmodules file in root dir.

**Comment by lerno** [comment]
Thank you!

**Pull request merged**
