### PR TITLE
Add qoi-c3

### PR DESCRIPTION
**Pull request by Hema2-official**
I've written a C3 implementation of QOI.
Do these changes seem right?
I'm asking because I didn't see source repositories linked to libraries before.
Also, would it be better to just mention QOI and link [my repo](https://github.com/Hema2-official/qoi-c3) to it? I think it would avoid having to update this repo on every release. (I provide .c3l releases there anyways.)

I opened a PR at [tonis2](https://github.com/tonis2)'s [Awesome.c3](https://github.com/tonis2/Awesome.c3) too, by the way.

peace<3

### CODE REVIEW

**Comment by lerno** [comment]
Vendor is intended for bindings for C libraries, so it's probably better to show it off in the discord and have it at Tonis' site.

**Comment by Hema2-official** [comment]
Okay, thanks for the clarification!
Since then, it got merged into [Awesome.c3](https://github.com/tonis2/Awesome.c3) and also [the official QOI repo](https://github.com/phoboslab/qoi)! So I'm quite happy with this.
I'll be back soon with some Lua bindings tho. :)

**Comment by lerno** [comment]
That's really cool. Since it's so small, maybe it's even a candidate for the stdlib in the future. Something to consider if you'd want it. How fast is the implementation compared to the reference C implementation?

**Comment by lerno** [comment]
Test using -O3/-O4/-O5 as well and compare to the throughput of the C version?

**Comment by Hema2-official** [comment]
I did more testing as you suggested.
I also rewritten the benchmark in pure C++ to measure original performance. I used MSCV to compile it.
The performance of qoi-c3 remained steady from O2 to O5, the only measurable differences were between O0, being sluggish, O1, performing very nicely and O2 reaching a bit more speed than O1.
So I settled on `-O3 --x86cpu=avx2-v2 --fp-math=fast` for the C3 compiler.
As for MSVC, I tested compilation using `/O2 /Ot /arch:AVX2 /fp:fast`.

Results on a smaller and a larger picture (also, again, a pure C++ and a pure C3 executable):
```
Running benchmark (C++)
qoi_test_images/dice.qoi 800x600
decode: 2.101 ms, 228.463 MPPS
encode: 3.744 ms, 128.205 MPPS

Running benchmark (C3)
qoi_test_images/dice.qoi 800x600
decode: 1.631 ms, 294.298 MPPS
encode: 2.341 ms, 205.041 MPPS
```
```
Running benchmark (C++)
qoi_test_images/phoboslab.org.qoi 1313x20667
decode: 86.717 ms, 312.923 MPPS
encode: 206.494 ms, 131.412 MPPS

Running benchmark (C3)
qoi_test_images/phoboslab.org.qoi 1313x20667
decode: 77.619 ms, 349.602 MPPS
encode: 128.771 ms, 210.729 MPPS
```

After seeing these, I tried looking for more MSVC optimizations but no luck. I couldn't _not_ outperform the original implementation. So I tried lowering C3's level to O1:
```
Running benchmark (C3)
qoi_test_images/phoboslab.org.qoi 1313x20667
decode: 89.361 ms, 303.665 MPPS
encode: 144.745 ms, 187.473 MPPS
```

Still in disbelief, I turned off any architectural and mathematical optimizations, and left O1 for c3c and /O2 for MSVC:
```
Running benchmark (C++)
qoi_test_images/phoboslab.org.qoi 1313x20667
decode: 82.967 ms, 327.067 MPPS
encode: 206.67 ms, 131.3 MPPS

Running benchmark (C3)
qoi_test_images/phoboslab.org.qoi 1313x20667
decode: 92.911 ms, 292.062 MPPS
encode: 152.410 ms, 178.045 MPPS
```

If you want the code I ran the tests with, I can publish it in a repo, but only if necessary cuz it's all messy.
I think it's very promising, to say at least. :)

Also, a sidenote, it was much-much more convenient writing the benchmark in C3 than in C++. Bleh.

Thoughts?

**Pull request closed without merging**
