### PR TITLE
OpenGL Bindings

### PR DESCRIPTION
**Pull request by ellipse12**
I was not sure if it was better to have multiple files or just one. So I added one file for each sub-module, I am willing to merge them together if necessary though.

### CODE REVIEW

**Comment by ellipse12** [comment]
I also was not sure what to link to in every version.

**Comment by lerno** [comment]
Oh, this was an interesting solution. So the idea was that to avoid the user having to specify a version, all are available and you pick from the versions you know are available?

**Comment by ellipse12** [comment]
Sort of? I believe the version number in the source is in reference to when the specific functions were added, as the earlier versions definitely do not have all of the functions of that version (e.g. fixed pipeline functions like glStart and glEnd are not included). I came from a background of using Java/LWJGL which does something similar with their bindings.

**Comment by ellipse12** [comment]
I could probably add the old functions, though it would likely take a little while longer.

**Comment by lerno** [comment]
There is the alternative to use the `env` so for `module opengl::gl13;` replace that by `module opengl @if(env::GL_VERSION >= 13);`. Another thing would be to have `module opengl13::gl` and then have each version essentially include the other and you'd import `module opengl15::gl` and you get everything

**Comment by ellipse12** [comment]
Is env defined in the project.json? or is it a separate custom module?

**Comment by lerno** [comment]
I am talking about std::core::env, which can be injected. Another option is to have `import opengl` in every module, and it then looks for the constant `opengl::VERSION` which a user of the module must define, so essentially:
```c
module opengl;
const int VERSION = 22;
module mycode;
...
```
This would work.

**Comment by ellipse12** [comment]
how do you inject it? (sorry I am still a bit new to C3)

**Comment by ellipse12** [comment]
Also as of this moment the bindings should be fully functional with the latest version of OpenGL.

**Comment by lerno** [comment]
Literally just placing these rows anywhere in your sources:
```c
module opengl;
const int VERSION = 22;
```

**Comment by ellipse12** [comment]
You can access it then through env?

**Comment by lerno** [comment]
That's not even needed if all opengl modules import this.

**Comment by ellipse12** [comment]
Do you mind explaining to me how it(injecting variables into env) works anyway, it may be useful in other ways.

**Comment by ellipse12** [comment]
I'll start working on supporting earlier versions

**Comment by lerno** [comment]
Basically all modules are extendable, so if your program adds something to some other module it's there.

**Comment by ellipse12** [comment]
Ooh ok so it's just like the opengl thing but with std::core::env

**Comment by ellipse12** [comment]
I have been looking around and I can't seem to find older versions of the OpenGL headers/ xml spec. Would it be alright if you just merged this pull request and I will work on trying to find sources for older versions.

**Comment by ellipse12** [comment]
Oh wait I found the previous versions. It will probably take a day or two to do all of them.

**Comment by ellipse12** [comment]
Finished adding all of the previous versions! I also tested it by making a simple triangle and everything seemed to work.

**Comment by lerno** [comment]
Awesome work!

**Pull request merged**
